# 1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [120]:
import pandas as pd 
import numpy as np 
from sklearn.datasets import load_iris
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")

In [121]:
dt = load_iris()

In [122]:
df = pd.DataFrame(dt.data , columns=dt.feature_names)

In [123]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [124]:
df['target'] = dt.target

In [125]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [126]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [127]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split

In [128]:
X = df.drop(labels=['target'] , axis =1)

In [129]:
y = df['target']

In [130]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [131]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [132]:
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size=0.3 , random_state=42)

In [133]:
knnc = KNeighborsClassifier(n_neighbors=5 , algorithm='auto')

In [134]:
knnc.fit(X_train , y_train)

KNeighborsClassifier()

In [135]:
y_pred = knnc.predict(X_test)

In [136]:
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

In [137]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


# Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [138]:
from sklearn.model_selection import cross_val_score , GridSearchCV

In [139]:
params = [{'n_neighbors': (5,6,7,8,9,10,11,12,13,14,15,16,17)}]

In [140]:
gcv = GridSearchCV(knnc , param_grid=params  , cv = 5)

In [141]:
gcv.fit(X_train , y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': (5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
                                          16, 17)}])

In [142]:
gcv.best_params_

{'n_neighbors': 7}

In [143]:
gcv.best_score_

0.9523809523809523

In [144]:
knnc2 = KNeighborsClassifier(n_neighbors=7, algorithm='auto')

In [145]:
scores = cross_val_score(knnc2,X ,y  , cv=5 )

In [146]:
final_score = np.mean(scores)

In [147]:
final_score

0.9800000000000001

# Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

In [148]:
# tip : load_boston dataset has been removed from the library so i will be using california_house_pricing data

In [149]:
from sklearn.datasets import fetch_california_housing
c_h = fetch_california_housing()


In [150]:
df1 = pd.DataFrame(c_h.data , columns=c_h.feature_names)

In [151]:
df1['t'] = c_h.target

In [152]:
df1.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude      t  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422

In [153]:
X = df1.drop(labels=['t'] , axis=1)
y = df1['t']


In [154]:
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size=0.3 , random_state=42)

In [155]:
from sklearn.neighbors import KNeighborsRegressor

In [156]:
knnr.fit(X_train , y_train)

KNeighborsRegressor()

In [157]:
y_pred = knnr.predict(X_test)

In [158]:
from sklearn.metrics import mean_absolute_error , r2_score , mean_squared_error

In [159]:
mae = mean_absolute_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)


In [160]:
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared (R2) Score: {r2}")
print(f"Mean Squared Error (MSE): {mse}")

Mean Absolute Error (MAE): 0.8217871040051679
R-squared (R2) Score: 0.1337849088797427
Mean Squared Error (MSE): 1.136942049088978


# Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.



from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a KNN Regressor
knn_regressor = KNeighborsRegressor(n_neighbors=5)  # You can adjust the number of neighbors (K)

# Fit the regressor to the scaled training data
knn_regressor.fit(X_train_scaled, y_train)

# Make predictions on the scaled test data
y_pred = knn_regressor.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2) Score: {r2}")

# Q7. Write a Python function to calculate the euclidean distance between two points.

In [165]:
def euclideanDist ( point1 , point2) :
    
    distance = np.sqrt(np.sum((np.array(point1) - np.array(point2))**2))
    
    return distance
    

# Q8 . Write a Python function to calculate the manhattan distance between two points.

In [166]:
def manhattan_distance(point1, point2):
   
    
    if len(point1) != len(point2):
        raise ValueError("Points must have the same dimensionality")

    # Calculate the Manhattan distance using NumPy
    distance = np.sum(np.abs(np.array(point1) - np.array(point2)))
    
    return distance

# Example usage:
point1 = [1, 2, 3]
point2 = [4, 5, 6]
distance = manhattan_distance(point1, point2)
print(f"Manhattan Distance: {distance}")

Manhattan Distance: 9


 # Q.5 Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a KNN Classifier with weighted voting
knn_classifier = KNeighborsClassifier(n_neighbors=5, weights='distance')  # You can adjust the number of neighbors (K)

# Fit the classifier to the training data
knn_classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = knn_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")


 # Q6. Implement a function to standardise the features before applying KNN classifier.